// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDyglQRgYtmfuVRsXSEn3p5_hzFr6jdC-s',
//     appId: '1:632066093183:web:d65b7a61bc1494acf04f4a',
//     messagingSenderId: '632066093183',
//     projectId: 'sportsapp-29e3f',
//     authDomain: 'sportsapp-29e3f.firebaseapp.com',
//     storageBucket: 'sportsapp-29e3f.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAsdBjkSprRy2-bmLPfGeaec-cuItE0DqI',
//     appId: '1:632066093183:android:4bf675f208456981f04f4a',
//     messagingSenderId: '632066093183',
//     projectId: 'sportsapp-29e3f',
//     storageBucket: 'sportsapp-29e3f.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyANACzRhIg82TUOohrohsVnGWum7RaT2MY',
//     appId: '1:632066093183:ios:a9abadfac5eb374df04f4a',
//     messagingSenderId: '632066093183',
//     projectId: 'sportsapp-29e3f',
//     storageBucket: 'sportsapp-29e3f.appspot.com',
//     iosClientId: '632066093183-72im7adh7hnnfsuoahp5ju1ttn2ljdoi.apps.googleusercontent.com',
//     iosBundleId: 'com.example.hslive',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyANACzRhIg82TUOohrohsVnGWum7RaT2MY',
//     appId: '1:632066093183:ios:a9abadfac5eb374df04f4a',
//     messagingSenderId: '632066093183',
//     projectId: 'sportsapp-29e3f',
//     storageBucket: 'sportsapp-29e3f.appspot.com',
//     iosClientId: '632066093183-72im7adh7hnnfsuoahp5ju1ttn2ljdoi.apps.googleusercontent.com',
//     iosBundleId: 'com.example.hslive',
//   );
// }
